#pragma once

#define STEELC_VERSION_STR "0.4.0-alpha";

#define STEELC_VERSION_MAJOR 0
#define STEELC_VERSION_MINOR 4
#define STEELC_VERSION_PATCH 0

#define STEELC_VERSION_PACKED ((STEELC_VERSION_MAJOR << 16) | (STEELC_VERSION_MINOR << 8) | (STEELC_VERSION_PATCH))