#pragma once

enum symbol_error {
	SYMBOL_OK = 0,

	// type symbol errors
	SYMBOL_CONFLICTS_WITH_FIELD,
	SYMBOL_CONFLICTS_WITH_METHOD,

	// generic symbol errors
	SYMBOL_CONFLICTS_WITH_VARIABLE,
	SYMBOL_CONFLICTS_WITH_GENERIC,
	SYMBOL_CONFLICTS_WITH_FUNCTION,
	SYMBOL_CONFLICTS_WITH_TYPE,
	SYMBOL_CONFLICTS_WITH_ENUM,
	SYMBOL_CONFLICTS_WITH_MODULE,

	// function symbol errors
	SYMBOL_CANNOT_OVERLOAD_BY_RETURN_TYPE,
};
