#pragma once

#define STEELC_VERSION_STR "0.5.0";

#define STEELC_VERSION_MAJOR 0
#define STEELC_VERSION_MINOR 5
#define STEELC_VERSION_PATCH 0

#define STEELC_VERSION_PACKED_U32 ((STEELC_VERSION_MAJOR << 16) | (STEELC_VERSION_MINOR << 8) | (STEELC_VERSION_PATCH))